### ISSUE TITLE
Species detected audio in Spotlight (Arbimon Insight) is not displaying

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#265]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1674176902923599?thread_ts=1674148911.224159&cid=C03FD1WD02J

**Description**

> we found another bug in Arbimon Insights. Not sure if this is related to those other issues in this ticket. Some species like this one https://bio.rfcx.org/cratere-degli-astroni-rns/spotlight/numenius-arquata have a template in Arbimon, but we can not see the species call in Arbimon Insights. But this issue could be because of the uploader, right? In any case, Huawei already posted part of the report in their blog, mentioning Arbimon Insights and including links for some species. We should please fix Arbimon Insights as soon as possible. 

![Image](https://user-images.githubusercontent.com/87486094/213622634-6ad2a1f5-90f7-4682-8e24-26cf83c4990d.png)

**Comment by rassokhina-e** [comment]
https://rfcx.slack.com/archives/C03FD1WD02J/p1674215820534259?thread_ts=1674148911.224159&cid=C03FD1WD02J

>Hi guys! 
[@Marconi](https://rfcx.slack.com/team/U0138TAU00J)
, you can not see this species audio: https://bio.rfcx.org/cratere-degli-astroni-rns/spotlight/numenius-arquata on the Insights page because the original recording, related to this template on the Arbimon side - non-core rfcx recording. I mean this is the old Arbimon recording which we do not keep in the core database. Originally, when the templates sync logic was built it was the requirement to support on the Insight page only those recordings which were uploaded with the Uploader app.
