### ISSUE TITLE
Files are duplicates when reupload

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#347]
Original post: https://rfcx.slack.com/archives/C05B3FC1ZFX/p1687257869444939

**Description**

Project: [La_Selva_Recordings_Rice_Beaudrot_Finneran_2023
](https://arbimon.rfcx.org/project/la-selva-recordings-rice-beaudrot-finneran-2023/dashboard)
We sent to analysis data for user to reupload. They reuploaded files then got back that they were still missing some data. We re-analyzed and resent her the details. When user reuploaded the files, user got duplicates error. 

We might need to check why user saw duplicate error.

Mahreen forwarded the email with files to Ant.

**Comment by rassokhin-s** [comment]
So the problem here is that user has uploaded two different files with the same timestamp into one stream. And our script shows that one of these files is corrupted.
Anyways even if user will reupload one of them (which is corrupted), the Media API won't work correctly because two files have the same timestamps in one stream: Media API will return a mix of those two files

**Comment by rassokhin-s** [comment]
<img width="1395" alt="Screenshot 2023-06-22 at 16 53 07" src="https://github.com/rfcx/engineering-support/assets/2122991/1bd3507c-9ebc-4ca5-a8a1-e91ef3eb6a47">
