### ISSUE TITLE
Add guardian name/id to export detection

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#521]
Original request https://rfcx.slack.com/archives/C03FD1WD02J/p1709919821880359 @krisharmon 

When downloading data from the Analytics page of the Guardian Dashboard, the excel sheet does not contain a column which specifies the Guardian name, (I'll add a screenshot).
Can we add the Guardian name as a column, it will show the name of the Guardian repeating down the column for every data point associated with it.

maybe include the Guardian ID and Arbimon site ID as well?

![Image](https://github.com/rfcx/engineering-support/assets/87486094/5dd5463f-0a96-48ab-9fb8-a650948d2fe3)

![Image](https://github.com/rfcx/engineering-support/assets/87486094/4c4c49ce-d366-4223-b4b2-a0164d591de2)

**Comment by Tooseriuz** [comment]
I don't think it is possible to add (guardian name, site name, id, etc) since each rows mean each hours so it is possible that in 1 hour, there could be multiple sites that associated in that hour.

And the current endpoint doesn't support it.
```
{
        "timeBucket": "2024-01-03T10:00:00.000Z",
        "aggregatedValue": 21,
        "firstStart": "2024-01-03T10:12:43.339Z",
        "lastStart": "2024-01-03T10:55:01.427Z",
        "classification": {
            "value": "chainsaw",
            "title": "Chainsaw",
            "image": null
        }
}
```

so if an operation team is interested to a specific site or guardian. they can choose each site and export the csv
